SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER Uptrig
AFTER DELETE
ON Inventory
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE(chr(10));
	DBMS_OUTPUT.PUT_LINE('Data are DELETED From Inventory(Calling Trigger)!!');
	DBMS_OUTPUT.PUT_LINE(chr(10));
END;
/